### ISSUE TITLE
GNB isActive 표시가 안되어 있는 페이지 수정

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Samcho#100]
## 📄 설명
GNB isActive 표시가 안되어 있는 페이지 수정

## 📋 TO-DO
- [x] mypage/photo 페이지
- [x] mypage/setting 페이지
- [x] chart/more 페이지
- [x] mypage/buddy-management 페이지
- [ ] diary/detail 페이지 GNB 대신 교환하기 NavBar로 변경
- [x] nav 섹션 요소에 적절한 제목 설정 필요

## 🔔 기타
기타 사항을 적어주세요.
