### ISSUE TITLE
TopNavigation 컴포넌트 수정

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Samcho#110]
## 📄 설명
<img width="317" alt="스크린샷 2024-09-05 16 23 57" src="https://github.com/user-attachments/assets/9c0f227b-083b-4131-a122-33169f6ea876">

단짝 관리 페이지 수정

## 📋 TO-DO
- [ ] TopNavigation 컴포넌트 수정
- [ ] 아이콘 컴포넌트를 버튼으로 감싸는 방향으로 수정
- [ ] 아이콘 컴포넌트는 aria-hidden={true}

## 🔔 기타
기타 사항을 적어주세요.
