### ISSUE TITLE
알림 페이지 마크업 및 NotificationCard 컴포넌트 마크업 

### ISSUE THREAD

**Issue by paintover** [FRONTENDSCHOOL10/Samcho#130]
## 📄 설명

알림 페이지 마크업 및 NotificationCard 컴포넌트 마크업\
![image](https://github.com/user-attachments/assets/5d181085-304a-4e65-9f71-9390e5e2f001)

## 📋 TO-DO

- [x] TopNavigation에 알림 페이지 연결
- [x] NotificationCard 컴포넌트 마크업  (type 2개)
- [x] 알림 페이지 마크업
