### ISSUE TITLE
알림 기능 구현

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Samcho#149]
## 📄 설명
알림 기능 구현

## 📋 TO-DO
- [x] notification 에서 현재 로그인한 id와 user 필드에 있는 아이디가 일치한 데이터만 가져와서 뿌려준다. 
- [ ] 수락버튼을 누를시 buddy 컬렉션에 두개의 데이터를 저장 해야한다. 또한, 알림 데이터를 삭제해야한다.
- [ ] 거절버튼을 누를시 알림 데이터를 삭제하도록 한다.

## 🔔 기타
일단 단짝 type만 구현 (아직 교환일기 신청 데이터가 없음)
