### ISSUE TITLE
단짝 관리 기능 구현

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Samcho#155]
## 📄 설명
단짝 관리 기능 구현

## 📋 TO-DO

- [x] 사용자와 단짝인 리스트를 모두 보여줘야함.
- [x] 단짝과 몇일째인지 표시 되어야 함.
- [x] 절교 버튼을 누를시 단짝 관계가 끊어져야 함.

## 🔔 기타

기타 사항을 적어주세요.
