### ISSUE TITLE
단짝 인원 수 나타내는 기능 구현

### ISSUE THREAD

**Issue by paintover** [FRONTENDSCHOOL10/Samcho#165]
## 📄 설명

![image](https://github.com/user-attachments/assets/7f83ec45-aaae-4aa4-99bf-d3fc3627a724)

## 📋 TO-DO

- [x] 로그인된 유저의 단짝 인원 수 나타내야 함.
- [x] 절교할 경우, 인원 수가 업데이트 되어야 함. 

## 🔔 기타
- [ ] 추후, 단짝 신청이 이루어질 경우에 인원 수가 업데이트 되어야 함.
