### ISSUE TITLE
일기 검색 페이지 검색 결과 월 별 구분 및 검색내역 기능 추가

### ISSUE THREAD

**Issue by heydoopal** [FRONTENDSCHOOL10/Samcho#173]
## 📄 설명
![image](https://github.com/user-attachments/assets/b92ba348-a3da-4df1-9e57-8d9f5bbaedc8)

현재 일기 검색 결과가 DiaryCard 컴포넌트로 일(day) 과 요일만 나오고 있어서 어느 달의 일기 인지 구분 안됨. 수정필요

## 📋 TO-DO

- [x] 일기 검색 페이지 검색 결과 월 별로 구분되게 수정
- [x] 검색 기록 내역 클릭 시 해당 검색어 검색될 수 있도록 기능 추가
- [x] 검색내역 개별 삭제 기능 누락되어있음. 추가하기
- [x] 페이지로 상태 다 끌어올리기

**Comment by heydoopal** [comment]
DiaryCard 선택 시 일기 상세로 넘어가게 해야함
