### ISSUE TITLE
교환일기 24시간 뒤 사라지도록 기능 구현

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Samcho#292]
## 📄 설명
교환일기 24시간 뒤 사라지도록 기능 구현
![image](https://github.com/user-attachments/assets/8b8724f6-74a0-44f7-a7b8-5b8cdbe03c5f)

## 📋 TO-DO

- [x] 교환일기 24시간 뒤 사라지도록 기능 구현
- [ ] 교환일기 카드 오른쪽 하단으로 날짜 이동
- [ ] 교환일기 카드 기존에 날짜 있던 자리에 경과시간 추가

## 🔔 기타

기타 사항을 적어주세요.
