### ISSUE TITLE
내정보 페이지에서 단짝 신청할 때 처리중인 경우 버튼 비활성화 필요 & 모바일 환경에서 단짝 검색 글자 줄바꿈되는 현상 수정

### ISSUE THREAD

**Issue by paintover** [FRONTENDSCHOOL10/Samcho#340]
## 📄 설명
1. 내정보 페이지에서 단짝 신청할 때 처리중인 경우 버튼 비활성화 필요 
2. 모바일에서 볼 때 너비가 줄면서 단짝 검색의 '검색' 버튼 글자가 줄바꿈됨.

## 📋 TO-DO
- [x] 단짝 신청 처리 중인 경우 버튼 비활성화 필요
- [x] 단짝 신청 후 대기 중인 경우 (사용자가 requester && pending) -> 신청 취소 버튼 (buddy 데이터 & notification 데이터 삭제)
- [x] 단짝 신청 받은 상황인 경우 (사용자가 recipient && pending) -> 신청 버튼 클릭 -> 토스트 (해당 사용자에게 단짝 신청을 받은 상황이라는 걸 알려주는 알림 띄우기)
- [x] 해당 사용자와 이미 단짝인 경우 -> 버튼 없애고 '현재 단짝 상태입니다' 텍스트 보일 수 있도록 수정  
- [x] 모바일에서 볼 때 단짝 검색의 '검색' 버튼 글지가 줄바꿈되는 거 수정

## 🔔 기타

기타 사항을 적어주세요.
