### ISSUE TITLE
Accordion 컴포넌트 마크업

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Samcho#41]
## 📄 설명
<img width="489" alt="스크린샷 2024-09-02 16 04 09" src="https://github.com/user-attachments/assets/d4965be8-b909-4fa2-bd29-8e5732118cd6">

## 📋 TO-DO
- [ ] 텍스트를 입력받아 아코디언 타이틀을 설정 할 수 있어야함.
- [ ] 열고 닫을수 있어야하며 버튼의 모양이 바뀌어야 함
- [ ] 아코디언을 열었을때 안의 요소들은 children으로 받는다.

## 🔔 기타
기타 사항을 적어주세요.
