### ISSUE TITLE
프로젝트 개발 관련 에셋 추가 및 컬러 토큰 추가

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Samcho#5]
## 📄 설명
프로젝트 개발 관련 에셋 추가 및 컬러 토큰 추가

## 📋 TO-DO
- [ ] 프로젝트 개발 관련 에셋 추가
- [ ] 프로젝트 개발 관련 컬러 토큰 추가
- [ ] 프로젝트 개발 환경 부족한 부분 보완
