### ISSUE TITLE
PostCard 컴포넌트 마크업

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Samcho#53]
## 📄 설명
<img width="529" alt="스크린샷 2024-09-03 14 35 13" src="https://github.com/user-attachments/assets/5f245015-222a-44ed-a8e6-7e5c431c7428">

## 📋 TO-DO
- [ ] 첫번째 카드는 우편함에서 쓰이는 타입의 카드입니다. 두번째 카드는 단짝 친구 요청탭에서 쓰이는 타입의 카드입니다. 타입별로 카드를 재사용 할 수 있어야 합니다.
- [ ] 체크, 휴지통, 수락, 거절 모두 버튼태그로 설계 되어야합니다.
- [ ] 안에 text는 prop으로 받아 설계 되어야 합니다.

## 🔔 기타
기타 사항을 적어주세요.
