### ISSUE TITLE
마이페이지 마크업

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Samcho#54]
## 📄 설명
<img width="327" alt="스크린샷 2024-09-03 14 38 15" src="https://github.com/user-attachments/assets/d724097e-e902-4a90-bfb3-40c78e612fa1">

## 📋 TO-DO
- [ ] 계정 카테고리의 박스 클릭시 계정관리 페이지로 이동되기 위해 Link 태그를 사용해야함
- [ ] 나의 카테고리의 박스 중 사진 모아보기 클릭시 사진 모아보기 페이지로 이동되기 위해 Link 태그를 사용해야함
- [ ] 단짝 카테고리의 관리 버튼 클릭시 단짝 관리 페이지로 이동되기 위해 Link 태그를 사용해야함
- [ ] 단짝 찾기 카테고리의 박스 안에는 인풋과 버튼으로 설계가 되어야함.

## 🔔 기타
기타 사항을 적어주세요.
