### ISSUE TITLE
Input 컴포넌트 웹 표준 및 접근성 개선

### ISSUE THREAD

**Issue by paintover** [FRONTENDSCHOOL10/Samcho#78]
## 📄 설명

Input 컴포넌트 웹 표준 및 접근성 개선

## 📋 TO-DO

- [x] rest props 사용 고려
- [x] 다시 정의될 필요 없는 코드들이라면 다시 정의될 필요가 없는 코드는 컴포넌트 외부로 이동
- [x] border-[1px] > border로 수정
