### ISSUE TITLE
단짝 관리 페이지 마크업

### ISSUE THREAD

**Issue by paintover** [FRONTENDSCHOOL10/Samcho#93]
## 📄 설명

![image](https://github.com/user-attachments/assets/fc21416e-c36a-4083-9cf4-0034b1bfb221)

## 📋 TO-DO

- [ ] 탭 변경에 따라 '나의 단짝', '단짝 요청' 컴포넌트가 렌더링되어야 함. 
- [ ] 마이페이지의 단짝 관리에서 페이지가 연결되어야 함. 
- [ ] 페이지 내에서 이전 페이지로 이동이 가능해야 함. 

## 🔔 기타

'나의 단짝'은 아직 디자인이 안된 상태라, 탭 변경만 가능하게 해두기로 함.
